settings = {
    'token': TOKEN,
    'bot': "Ticket Bot",
    'id': ID,
    'prefix': '!',
    'number_of_questions':3,
    'start_msg_question':'Твой вопрос:',
    'question1':'Первый вопрос',
    'right_answer_question1':'1',
    'question2':'Второй вопрос',
    'right_answer_question2':'2',
    'question3':'Третий вопрос',
    'right_answer_question3':'3',
    'end_test':'Спасибо за прохождение опроса!\nЧтобы узнать результат, напиши !result',
    'limit_top':5,
    'name_table':'Топ по количеству очков',
    'no_user_in_top':'Еще никто не прошел тест :(\nТы можешь быть первым!',
    'start_msg_top':'Топ',
    'result_no_user':'Чтобы узнать результаты, нужно пройти опрос.\nНачать опрос можно по команде !start',
    'result_no_end_test':'Чтобы узнать результ, нужно пройти тест до конца! ',
    'result_right_answer_start':'Ты ответил правильно на ',
    'result_right_answer_end':' вопроса',
    'title_help':'Команды',
    'value_start':'Начать тест',
    'value_result':'Узнать результаты',
    'start_no_end_test':'Закончи тест',
    'user_already_answered':'Ты уже ответил',
    'id_role_admin': 780508195155214336,
    'id_message_with_info': 0000,
    'emb_msg_title':'Инструкция',
    'emb_field_name':'нажми на реакцию',
    'emb_field_value':'чтобы начать тест',
    'emoji_id': 791352526842626048,
    'send_text':'Привет! Чтобы начать тест напиши !start',
    'on_msg_no_user':'Чтобы начать опрос, напиши !start\nЧтобы узнать команды, напиши !help',
    'om_msg_user_already_answered':'Ты уже ответил'
}
